#ifndef COLORBUFFERINFO_H
#define COLORBUFFERINFO_H


typedef enum { COLOR_BUFFER_LUMINANCE, COLOR_BUFFER_RGBA, COLOR_BUFFER_BGRA, COLOR_BUFFER_BGR } ColorBufferType;


#define WIDTH_FOR_CAMERA_CROP 800
#define HEIGHT_FOR_CAMERA_CROP 600
#define COLOR_DEPTH_FOR_CAMERA_CROP 1
#define FRAMESIZE_FOR_CAMERA_CROP (WIDTH_FOR_CAMERA_CROP * HEIGHT_FOR_CAMERA_CROP * COLOR_DEPTH_FOR_CAMERA_CROP )
#define CAMERA_CROP_BUFFER_POOL_ID 100


#define WIDTH_FOR_OPENCV 320
#define HEIGHT_FOR_OPENCV 240
#define COLOR_DEPTH_FOR_OPENCV 1
#define FRAMESIZE_FOR_OPENCV (WIDTH_FOR_OPENCV * HEIGHT_FOR_OPENCV * COLOR_DEPTH_FOR_OPENCV )

#define OPENCV_BUFFER_POOL_ID   0

#define WIDTH_FOR_EYEDETECT_VIEW 320
#define HEIGHT_FOR_EYEDETECT_VIEW 240
#define COLOR_DEPTH_FOR_EYEDETECT_VIEW 4
#define FRAMESIZE_FOR_EYEDETECT_VIEW (WIDTH_FOR_EYEDETECT_VIEW *HEIGHT_FOR_EYEDETECT_VIEW * COLOR_DEPTH_FOR_EYEDETECT_VIEW)

#define EYEDETECT_VIEW_BUFFER_POOL_ID   1

#define WIDTH_FOR_CAMERA_FRAME 2608
#define HEIGHT_FOR_CAMERA_FRAME 1960
#define COLOR_DEPTH_FOR_CAMERA_FRAME 1
#define FRAMESIZE_FOR_CAMERA_FRAME (WIDTH_FOR_CAMERA_FRAME *HEIGHT_FOR_CAMERA_FRAME * COLOR_DEPTH_FOR_CAMERA_FRAME)

#define CAMERA_FRAME_BUFFER_POOL_ID 2

#define WIDTH_FOR_EYE_VIEW 640
#define HEIGHT_FOR_EYE_VIEW 480
#define COLOR_DEPTH_FOR_EYE_VIEW 1
#define FRAMESIZE_FOR_EYE_VIEW (WIDTH_FOR_EYEDETECT_VIEW *HEIGHT_FOR_EYEDETECT_VIEW * COLOR_DEPTH_FOR_EYEDETECT_VIEW)

#define EYE_VIEW_BUFFER_POOL_ID   3


#define ROI_X 904
#define ROI_Y 680

#define OPENCV_FRAME_CENTER_X 160
#define OPENCV_FRAME_CENTER_Y 120

#define CROP_FRAME_CENTER_X  400
#define CROP_FRAME_CENTER_Y  300

#endif // COLORBUFFERINFO_H
