#include "multicorequeuetemplate.h"

EnrollMultiCoreQueue   gEnrollMultiCoreQueue;
EyeSelectMultiCoreQueue gEyeSelectMultiCoreQueue;
EnrollMultiCoreQueue   gIdentifyMultiCoreQueue;
NeuroMultiCoreQueue	gNeuroMultiCoreQueue;